[phases.setup]
nixPkgs = ["python311", "gcc"]
aptPkgs = ["python3-pip", "python3-venv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && PYTHONPATH=/app uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app" 